const initialTiles = [
  {
    text: "waiting at dawn",
    color: "#f02400",
    day: 0,
    startTime: 0,
    endTime: 4,
    id: 66890,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 0,
      dy: 4,
    },
  },
  {
    text: "consider prayer",
    color: "#33b679",
    day: 0,
    startTime: 6,
    endTime: 7,
    id: 87010,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 1,
    },
  },
  {
    text: "the concrete cracks",
    color: "#f02400",
    day: 0,
    startTime: 12,
    endTime: 16,
    id: 98762,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 12,
      dy: 4,
    },
  },
  {
    text: "and hisses",
    color: "#f02400",
    day: 0,
    startTime: 14,
    endTime: 17,
    id: 61595,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 14,
      dy: 3,
    },
  },
  {
    text: "plan week hour by hour",
    color: "#cd60eb",
    day: 0,
    startTime: 19,
    endTime: 21,
    id: 75167,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 19,
      dy: 2,
    },
  },
  {
    text: "run",
    color: "#4285f4",
    day: 3,
    startTime: 6,
    endTime: 8,
    id: 40432,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 2,
    },
  },
  {
    text: "look at the ceiling from the couch",
    color: "#ff7c1f",
    day: 3,
    startTime: 13,
    endTime: 18,
    id: 33608,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 13,
      dy: 5,
    },
  },
  {
    text: "try todo list app",
    color: "#33b679",
    day: 3,
    startTime: 19,
    endTime: 22,
    id: 60412,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 19,
      dy: 3,
    },
  },
  {
    text: "time and time again",
    color: "#f02400",
    day: 4,
    startTime: 0,
    endTime: 4,
    id: 79587,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 0,
      dy: 4,
    },
  },
  {
    text: "eat a modest lunch",
    color: "#33b679",
    day: 4,
    startTime: 8,
    endTime: 9,
    id: 61058,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 8,
      dy: 1,
    },
  },
  {
    text: "therapy",
    color: "#cd60eb",
    day: 4,
    startTime: 14,
    endTime: 16,
    id: 56104,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 2,
    },
  },
  {
    text: "call your brother",
    color: "#ff7c1f",
    day: 4,
    startTime: 20,
    endTime: 22,
    id: 29025,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 20,
      dy: 2,
    },
  },
  {
    text: "clean, again",
    color: "#33b679",
    day: 4,
    startTime: 21,
    endTime: 23,
    id: 46700,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 21,
      dy: 2,
    },
  },
  {
    text: "doubt yourself",
    color: "#f6bf26",
    day: 6,
    startTime: 2,
    endTime: 5,
    id: 94937,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 2,
      dy: 3,
    },
  },
  {
    text: "in hot air",
    color: "#f02400",
    day: 6,
    startTime: 14,
    endTime: 18,
    id: 1957,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 4,
    },
  },
  {
    text: "I find myself here",
    color: "#f02400",
    day: 5,
    startTime: 4,
    endTime: 7,
    id: 40473,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 4,
      dy: 3,
    },
  },
  {
    text: "out of time",
    color: "#f02400",
    day: 5,
    startTime: 10,
    endTime: 13,
    id: 17430,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 10,
      dy: 3,
    },
  },
  {
    text: "write down what you did instead",
    color: "#ff7c1f",
    day: 5,
    startTime: 17,
    endTime: 19,
    id: 58855,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 17,
      dy: 2,
    },
  },
  {
    text: "write down your dreams",
    color: "#33b679",
    day: 2,
    startTime: 1,
    endTime: 3,
    id: 98053,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 1,
      dy: 2,
    },
  },
  {
    text: "meditate",
    color: "#cd60eb",
    day: 2,
    startTime: 16,
    endTime: 17,
    id: 8881,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 16,
      dy: 1,
    },
  },
  {
    text: "clean",
    color: "#ff7c1f",
    day: 2,
    startTime: 17,
    endTime: 18,
    id: 57517,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 17,
      dy: 1,
    },
  },
  {
    text: "scroll",
    color: "#4285f4",
    day: 2,
    startTime: 18,
    endTime: 19,
    id: 44579,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 18,
      dy: 1,
    },
  },
  {
    text: "buy the same groceries again",
    color: "#cd60eb",
    day: 1,
    startTime: 3,
    endTime: 5,
    id: 79836,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 3,
      dy: 2,
    },
  },
  {
    text: "as the ground heats up",
    color: "#f02400",
    day: 1,
    startTime: 6,
    endTime: 9,
    id: 64723,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 3,
    },
  },
  {
    text: 'make a plan to get "out" of "this"',
    color: "#33b679",
    day: 1,
    startTime: 14,
    endTime: 17,
    id: 69126,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 3,
    },
  },
  {
    text: "flip through The Savage God at the library",
    color: "#4285f4",
    day: 2,
    startTime: 10,
    endTime: 13,
    id: 37791,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 10,
      dy: 3,
    },
  },
  {
    text: "buy another planner",
    color: "#f6bf26",
    day: 1,
    startTime: 19,
    endTime: 22,
    id: 37058,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 19,
      dy: 3,
    },
  },
]

export default initialTiles
