const initialTiles3 = [
  {
    text: "I believe there is a father",
    color: "#cd60eb",
    day: 0,
    startTime: 0,
    endTime: 12,
    id: 71337,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 0,
      dy: 12,
    },
  },
  {
    text: "on Sunday morning",
    color: "#33b679",
    day: 0,
    startTime: 0,
    endTime: 2,
    id: 14591,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 0,
      dy: 2,
    },
  },
  {
    text: "sitting in silence",
    color: "#ff7c1f",
    day: 0,
    startTime: 2,
    endTime: 4,
    id: 77940,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 2,
      dy: 2,
    },
  },
  {
    text: "worshipping a god that cannot love",
    color: "#f02400",
    day: 0,
    startTime: 4,
    endTime: 8,
    id: 40543,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 4,
      dy: 4,
    },
  },
  {
    text: "with a family that knows no better",
    color: "#f6bf26",
    day: 0,
    startTime: 8,
    endTime: 12,
    id: 90108,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 8,
      dy: 4,
    },
  },
  {
    text: "I believe there is a son",
    color: "#f02400",
    day: 0,
    startTime: 12,
    endTime: 24,
    id: 29275,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 12,
      dy: 12,
    },
  },
  {
    text: "waiting",
    color: "#33b679",
    day: 0,
    startTime: 12,
    endTime: 16,
    id: 19650,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 12,
      dy: 4,
    },
  },
  {
    text: "for divine intervention",
    color: "#4285f4",
    day: 0,
    startTime: 16,
    endTime: 20,
    id: 7268,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 16,
      dy: 4,
    },
  },
  {
    text: "to take me",
    color: "#4285f4",
    day: 0,
    startTime: 20,
    endTime: 22,
    id: 60533,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 20,
      dy: 2,
    },
  },
  {
    text: "out of myself",
    color: "#ff7c1f",
    day: 0,
    startTime: 22,
    endTime: 24,
    id: 89773,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 22,
      dy: 2,
    },
  },
  {
    text: "waiting for dawn",
    color: "#cd60eb",
    day: 6,
    startTime: 0,
    endTime: 5,
    id: 18517,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 0,
      dy: 5,
    },
  },
  {
    text: "the concrete cracks",
    color: "#ff7c1f",
    day: 6,
    startTime: 5,
    endTime: 7,
    id: 55091,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 5,
      dy: 2,
    },
  },
  {
    text: "and hisses",
    color: "#33b679",
    day: 6,
    startTime: 7,
    endTime: 10,
    id: 16472,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 7,
      dy: 3,
    },
  },
  {
    text: "as the ground heats up",
    color: "#f02400",
    day: 6,
    startTime: 10,
    endTime: 14,
    id: 68137,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 10,
      dy: 4,
    },
  },
  {
    text: "time and time again",
    color: "#4285f4",
    day: 6,
    startTime: 14,
    endTime: 18,
    id: 71290,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 4,
    },
  },
  {
    text: "I find myself here",
    color: "#cd60eb",
    day: 6,
    startTime: 18,
    endTime: 20,
    id: 41944,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 18,
      dy: 2,
    },
  },
  {
    text: "out of time",
    color: "#f6bf26",
    day: 6,
    startTime: 20,
    endTime: 23,
    id: 30897,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 20,
      dy: 3,
    },
  },
  {
    text: "in hot air",
    color: "#f02400",
    day: 6,
    startTime: 23,
    endTime: 24,
    id: 22393,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 23,
      dy: 1,
    },
  },
  // {
  //   text: "working",
  //   color: "#cd60eb",
  //   day: 2,
  //   startTime: 0,
  //   endTime: 8,
  //   id: 95195,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0,
  //     y: 0,
  //     dy: 8,
  //   },
  // },
  // {
  //   text: "working",
  //   color: "#33b679",
  //   day: 2,
  //   startTime: 8,
  //   endTime: 16,
  //   id: 85686,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0,
  //     y: 8,
  //     dy: 8,
  //   },
  // },
  // {
  //   text: "working",
  //   color: "#f6bf26",
  //   day: 2,
  //   startTime: 16,
  //   endTime: 24,
  //   id: 5758,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0,
  //     y: 16,
  //     dy: 8,
  //   },
  // },
  // {
  //   text: "grieving for my grandmother",
  //   color: "#f02400",
  //   day: 2,
  //   startTime: 0,
  //   endTime: 5,
  //   id: 22815,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0.5,
  //     y: 0,
  //     dy: 5,
  //   },
  // },
  // {
  //   text: "grieving for lost time",
  //   color: "#ff7c1f",
  //   day: 2,
  //   startTime: 5,
  //   endTime: 11,
  //   id: 56611,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0.5,
  //     y: 5,
  //     dy: 6,
  //   },
  // },
  // {
  //   text: "grieving for lost love",
  //   color: "#f02400",
  //   day: 2,
  //   startTime: 11,
  //   endTime: 18,
  //   id: 30810,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0.5,
  //     y: 11,
  //     dy: 7,
  //   },
  // },
  // {
  //   text: "grieving for my lost self",
  //   color: "#33b679",
  //   day: 2,
  //   startTime: 18,
  //   endTime: 24,
  //   id: 40948,
  //   opacity: 1,
  //   position: {
  //     dx: 0.5,
  //     x: 0.5,
  //     y: 18,
  //     dy: 6,
  //   },
  // },
]

const initialTiles2 = [
  {
    text: "waiting for dawn",
    color: "#f02400",
    day: 0,
    startTime: 0,
    endTime: 3,
    id: 66416,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 0,
      dy: 3,
    },
  },
  {
    text: "on a new day",
    color: "#f02400",
    day: 0,
    startTime: 1,
    endTime: 4,
    id: 6224,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 1,
      dy: 3,
    },
  },
  {
    text: "as the ground heats up",
    color: "#f02400",
    day: 2,
    startTime: 6,
    endTime: 12,
    id: 21073,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 6,
    },
  },
  {
    text: "time and time again",
    color: "#f02400",
    day: 3,
    startTime: 8,
    endTime: 14,
    id: 14593,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 7,
      dy: 7,
    },
  },
  {
    text: "the concrete cracks",
    color: "#f02400",
    day: 1,
    startTime: 3,
    endTime: 7,
    id: 11067,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 3,
      dy: 4,
    },
  },
  {
    text: "and hisses",
    color: "#f02400",
    day: 1,
    startTime: 5,
    endTime: 9,
    id: 52595,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 5,
      dy: 4,
    },
  },
  {
    text: "I find myself here",
    color: "#f02400",
    day: 4,
    startTime: 10,
    endTime: 16,
    id: 48030,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 10,
      dy: 6,
    },
  },
  // {
  //   text: "startup",
  //   color: "#4285f4",
  //   day: 0,
  //   startTime: 22,
  //   endTime: 24,
  //   id: 67517,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 22,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "art",
  //   color: "#33b679",
  //   day: 0,
  //   startTime: 20,
  //   endTime: 22,
  //   id: 79560,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 20,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "mental health",
  //   color: "#ff7c1f",
  //   day: 0,
  //   startTime: 18,
  //   endTime: 20,
  //   id: 82232,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 18,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "rationalizing",
  //   color: "#4285f4",
  //   day: 1,
  //   startTime: 22,
  //   endTime: 24,
  //   id: 90447,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 22,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "analyzing",
  //   color: "#f6bf26",
  //   day: 2,
  //   startTime: 22,
  //   endTime: 24,
  //   id: 59256,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 22,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "wishing I were someone else",
  //   color: "#cd60eb",
  //   day: 1,
  //   startTime: 20,
  //   endTime: 22,
  //   id: 98385,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 20,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "leaving behind a home",
  //   color: "#33b679",
  //   day: 0,
  //   startTime: 14,
  //   endTime: 16,
  //   id: 4344,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 14,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "leaving behind a god",
  //   color: "#4285f4",
  //   day: 1,
  //   startTime: 16,
  //   endTime: 18,
  //   id: 4555,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 16,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "leaving behind love",
  //   color: "#cd60eb",
  //   day: 2,
  //   startTime: 18,
  //   endTime: 20,
  //   id: 59482,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 18,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "leaving behind family",
  //   color: "#f6bf26",
  //   day: 3,
  //   startTime: 20,
  //   endTime: 22,
  //   id: 46833,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 20,
  //     dy: 2,
  //   },
  // },
  // {
  //   text: "leaving behind myself",
  //   color: "#cd60eb",
  //   day: 4,
  //   startTime: 22,
  //   endTime: 24,
  //   id: 37759,
  //   opacity: 1,
  //   position: {
  //     dx: 1,
  //     x: 0,
  //     y: 22,
  //     dy: 2,
  //   },
  // },
  {
    text: "out of time",
    color: "#f02400",
    day: 5,
    startTime: 12,
    endTime: 18,
    id: 8004,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 12,
      dy: 6,
    },
  },
  {
    text: "in hot air",
    color: "#f02400",
    day: 6,
    startTime: 15,
    endTime: 20,
    id: 55040,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 18,
      dy: 6,
    },
  },
]

const initialTiles = [
  {
    text: "I believe there is a father",
    color: "#cd60eb",
    day: 0,
    startTime: 0,
    endTime: 12,
    id: 71337,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 0,
      dy: 12,
    },
  },
  {
    text: "on Sunday morning",
    color: "#33b679",
    day: 0,
    startTime: 0,
    endTime: 2,
    id: 14591,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 0,
      dy: 2,
    },
  },
  {
    text: "sitting in silence",
    color: "#ff7c1f",
    day: 0,
    startTime: 2,
    endTime: 4,
    id: 77940,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 2,
      dy: 2,
    },
  },
  {
    text: "worshipping a god that cannot love",
    color: "#f02400",
    day: 0,
    startTime: 4,
    endTime: 8,
    id: 40543,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 4,
      dy: 4,
    },
  },
  {
    text: "with a family that knows no better",
    color: "#f6bf26",
    day: 0,
    startTime: 8,
    endTime: 12,
    id: 90108,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 8,
      dy: 4,
    },
  },
  {
    text: "I believe there is a son",
    color: "#f02400",
    day: 0,
    startTime: 12,
    endTime: 24,
    id: 29275,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 12,
      dy: 12,
    },
  },
  {
    text: "waiting",
    color: "#33b679",
    day: 0,
    startTime: 12,
    endTime: 16,
    id: 19650,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 12,
      dy: 4,
    },
  },
  {
    text: "for divine intervention",
    color: "#4285f4",
    day: 0,
    startTime: 16,
    endTime: 20,
    id: 7268,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 16,
      dy: 4,
    },
  },
  {
    text: "to take me",
    color: "#4285f4",
    day: 0,
    startTime: 20,
    endTime: 22,
    id: 60533,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 20,
      dy: 2,
    },
  },
  {
    text: "out of myself",
    color: "#ff7c1f",
    day: 0,
    startTime: 22,
    endTime: 24,
    id: 89773,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 22,
      dy: 2,
    },
  },
  {
    text: "waiting for dawn",
    color: "#cd60eb",
    day: 6,
    startTime: 0,
    endTime: 5,
    id: 18517,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 0,
      dy: 5,
    },
  },
  {
    text: "the concrete cracks",
    color: "#ff7c1f",
    day: 6,
    startTime: 5,
    endTime: 7,
    id: 55091,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 5,
      dy: 2,
    },
  },
  {
    text: "and hisses",
    color: "#33b679",
    day: 6,
    startTime: 7,
    endTime: 10,
    id: 16472,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 7,
      dy: 3,
    },
  },
  {
    text: "as the ground heats up",
    color: "#f02400",
    day: 6,
    startTime: 10,
    endTime: 14,
    id: 68137,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 10,
      dy: 4,
    },
  },
  {
    text: "time and time again",
    color: "#4285f4",
    day: 6,
    startTime: 14,
    endTime: 18,
    id: 71290,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 4,
    },
  },
  {
    text: "I find myself here",
    color: "#cd60eb",
    day: 6,
    startTime: 18,
    endTime: 20,
    id: 41944,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 18,
      dy: 2,
    },
  },
  {
    text: "out of time",
    color: "#f6bf26",
    day: 6,
    startTime: 20,
    endTime: 23,
    id: 30897,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 20,
      dy: 3,
    },
  },
  {
    text: "in hot air",
    color: "#f02400",
    day: 6,
    startTime: 23,
    endTime: 24,
    id: 22393,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 23,
      dy: 1,
    },
  },
  {
    text: "art",
    color: "#33b679",
    day: 2,
    startTime: 6,
    endTime: 14,
    id: 71031,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 8,
    },
  },
  {
    text: "创造新作品",
    color: "#cd60eb",
    day: 2,
    startTime: 14,
    endTime: 20,
    id: 19897,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 14,
      dy: 6,
    },
  },
  {
    text: "cutting corners",
    color: "#f02400",
    day: 2,
    startTime: 5,
    endTime: 6,
    id: 39037,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 5,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#4285f4",
    day: 2,
    startTime: 4,
    endTime: 5,
    id: 97376,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 4,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#f6bf26",
    day: 2,
    startTime: 20,
    endTime: 21,
    id: 92853,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 20,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#ff7c1f",
    day: 2,
    startTime: 21,
    endTime: 22,
    id: 11988,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 21,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#ff7c1f",
    day: 3,
    startTime: 4,
    endTime: 5,
    id: 41136,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 4,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#f02400",
    day: 3,
    startTime: 5,
    endTime: 6,
    id: 89441,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 5,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#f02400",
    day: 3,
    startTime: 21,
    endTime: 22,
    id: 12735,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 21,
      dy: 1,
    },
  },
  {
    text: "cutting corners",
    color: "#33b679",
    day: 3,
    startTime: 20,
    endTime: 21,
    id: 17582,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 20,
      dy: 1,
    },
  },
  {
    text: "startup",
    color: "#4285f4",
    day: 3,
    startTime: 6,
    endTime: 20,
    id: 47589,
    opacity: 1,
    position: {
      dx: 1,
      x: 0,
      y: 6,
      dy: 14,
    },
  },
  {
    text: "looking for shortcuts",
    color: "#cd60eb",
    day: 4,
    startTime: 4,
    endTime: 22,
    id: 21409,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0.5,
      y: 4,
      dy: 18,
    },
  },
  {
    text: "unlearning myself",
    color: "#ff7c1f",
    day: 4,
    startTime: 4,
    endTime: 22,
    id: 1111,
    opacity: 1,
    position: {
      dx: 0.5,
      x: 0,
      y: 4,
      dy: 18,
    },
  },
]

export default initialTiles
